export enum UserStatus {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  DECLINED = 'DECLINED',
  VERIFIED = 'VERIFIED',
  UNVERIFIED = 'UNVERIFIED',
  DEACTIVATED = 'DEACTIVATED',
  DELETED = 'DELETED',
}
